#!/usr/bin/env bash



   
           [[ -z "$1" ]] && { exit 1; }
            TARGET_DIR="$1"
  
           [[ ! -d "$TARGET_DIR" ]] && { echo "[!] Directory not found, exiting.."; exit 1; }
           BACKUP_DIR="$TARGET_DIR/backup_$(date +%Y%m%d_%H%M%S)"
           mkdir -p "$BACKUP_DIR" && echo "[*] Backup folder created: $BACKUP_DIR"
           cp -a "$TARGET_DIR"/* "$BACKUP_DIR" 2>/dev/null && echo "[*] Backup completed." 




