#!/usr/bin/env bash

       
        

         command -v python3 >/dev/null || { sudo apt update && sudo apt install -y python3 python3-venv python3-pip; }
         
         python3 -m venv venv || { echo "failed to create the environment, exiting.."; exit 1; }
          source venv/bin/activate || { echo "failed to activate the environment, exiting.."; exit 1; }

              for item in "$@"; do
                     pip install "$item" || { echo "installation failed, exiting.."; exit 1; }
                     pip freeze | grep "$item" >> requirements.txt
                 done
                  echo "[+]python environment set."
