#!/usr/bin/env bash 




 [[ $EUID -ne 0 ]] && { echo "[!] run as root in order to run the script"; exit 1; }
 command -v sshd >/dev/null  || { echo "[!] sshd not installed"; exit 1; }

if command -v systemctl >/dev/null; then
     if ! systemctl is-active --quiet ssh 2>/dev/null &&
        ! systemctl is-active --quiet sshd 2>/dev/null; then
                echo "[!] SSH service not running"
             exit 1
     fi
fi

  [[ ! -f /var/log/auth.log ]] && { echo "[!]WARNING: auth.log file not found."; }



#catching SSH connections
while true; do

LIST_IPS=$(ss -tnp | awk '/sshd/ {print $5}' | cut -d: -f1 | sort -u | sed 's/^/ - /')
      [[ -z "$LIST_IPS" ]] && { LIST_IPS="No active SSH connections"; }
   
     echo "________________________________"  
     echo "[*] ACTIVE CONNECTIONS VIA  SSH:"
      printf "%s\n" "$LIST_IPS"
     echo "________________________________"  
 sleep 15
clear
done
